error is
error: lifetime may not live long enough
    --> src/core/mempool.rs:1242:13
     |
1235 |         conn: &DBConn,
     |               - let's call the lifetime of this reference `'1`
...
1242 |             fee_rate_transactions,
     |             ^^^^^^^^^^^^^^^^^^^^^ cast requires that `'1` must outlive `'static`

error[E0502]: cannot borrow `self.cost_estimator` as mutable because it is also borrowed as immutable
    --> src/core/mempool.rs:1405:61
     |
1353 |         let connection = self.conn();
     |                          ----------- immutable borrow occurs here
...
1362 |         for tx_reduced_info in db_txs {
     |                                ------ a temporary with access to the immutable borrow is created here ...
...
1405 |             let inside_result = todo(clarity_tx, &consider, self.cost_estimator.as_mut());
     |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
...
1425 |         }
     |         - ... and the immutable borrow might be used here, when that temporary is dropped and runs the destructor for type `Box<dyn Iterator<Item = MemPoolTxMinimalInfo>>`

r Please enter the commit message for your changes. Lines starting