error[E0499]: cannot borrow `*clarity_tx` as mutable more than once at a time     --> src/core/mempool.rs:1256:38      | 1218 |             clarity_tx,      |             ---------- first mutable borrow occurs here ... 1225 |         for tx_reduced_info in db_txs {      |                                ------ a temporary with access to the first borrow is created here ... ... 1256 |             let inside_result = todo(clarity_tx, &consider, self.cost_estimator.as_mut());      |                                      ^^^^^^^^^^ second mutable borrow occurs here ... 1276 |         }      |         - ... and the first borrow might be used here, when that temporary is dropped and runs the destructor for type `Box<dyn Iterator<Item = MemPoolTxMinimalInfo>>`